version: "3.9"
services:
  app:
    image: httpd:latest
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs
    networks:
      - web

networks:
  web:
    driver: bridge
